import { CONTRACT } from '../index'

describe('Assembly compilation:', () => {
    it('should optimize: all api T_EXT_FUN', () => {
        /* this is source code for test:
            #include APIFunctions\n#pragma verboseAssembly\n// #pragma optimizationLevel 3\n\nlong testID, a, b;\n\nswitch (testID) {\ncase 1: // Clear_A\n    Clear_A();\n    Set_A2(0);\n    Clear_A();\n    break;\ncase 2: // Clear_B\n    Clear_B();\n    Set_B4(0);\n    Clear_B();\ncase 3: // Clear_A_And_B\n    Set_A1_A2(0, 0); Set_A3_A4(0, 0); Clear_B();\n    Clear_A_And_B();\n    Clear_B();\n    break;\ncase 4: // Swap_A_and_B\n    Clear_A_And_B();\n    a++;\n    Swap_A_and_B();\n    a++;\n    Set_B4(0);\n    Set_A3(0);\n    break;\ncase 5: // metaDoNothing\n    Clear_A_And_B();\n    Send_All_To_Address_In_B();\n    Clear_A_And_B();\n    break;\ncase 6: // metaUnknowSuperRegisterA\n    Set_A3(a); Set_B3(a);\n    Put_Last_Block_GSig_In_A();\n    Set_A3(a); Set_B3(a);\n    break;\ncase 7: // metaUnknowSuperRegisterB\n    Set_A3(a); Set_B3(a);\n    OR_B_with_A();\n    Set_A3(a); Set_B3(a);\n    break;\ncase 8: // metaUB1ZB2ZB3ZB4\n    Set_B1_B2(a, 0);\n    B_To_Address_Of_Tx_In_A();\n    Set_B1(a); Set_B2(0); Set_B3(0); Set_B4(0);\n    break;\n}\n
        */
        const code = [
            '^declare r0',
            '^declare r1',
            '^declare r2',
            '^declare testID',
            '^declare a',
            '^declare b',
            '',
            '^comment line 7 switch (testID) {',
            'SET @r0 #0000000000000001',
            'BEQ $testID $r0 :__switch1_0',
            'SET @r0 #0000000000000002',
            'BEQ $testID $r0 :__switch1_1',
            'SET @r0 #0000000000000003',
            'BEQ $testID $r0 :__switch1_2',
            'SET @r0 #0000000000000004',
            'BEQ $testID $r0 :__switch1_3',
            'SET @r0 #0000000000000005',
            'BEQ $testID $r0 :__switch1_4',
            'SET @r0 #0000000000000006',
            'BEQ $testID $r0 :__switch1_5',
            'SET @r0 #0000000000000007',
            'BEQ $testID $r0 :__switch1_6',
            'SET @r0 #0000000000000008',
            'BEQ $testID $r0 :__switch1_7',
            'FIN',
            '^comment line 8 case 1: // Clear_A',
            '__switch1_0:',
            '^comment line 9     Clear_A();',
            'FUN clear_A',
            '^comment line 10     Set_A2(0);',
            'CLR @r0',
            'FUN set_A2 $r0',
            '^comment line 11     Clear_A();',
            'FUN clear_A',
            '^comment line 12     break;',
            'FIN',
            '^comment line 13 case 2: // Clear_B',
            '__switch1_1:',
            '^comment line 14     Clear_B();',
            'FUN clear_B',
            '^comment line 15     Set_B4(0);',
            'CLR @r0',
            'FUN set_B4 $r0',
            '^comment line 16     Clear_B();',
            'FUN clear_B',
            '^comment line 17 case 3: // Clear_A_And_B',
            '__switch1_2:',
            '^comment line 18     Set_A1_A2(0',
            'CLR @r0',
            'CLR @r1',
            'FUN set_A1_A2 $r0 $r1',
            'CLR @r0',
            'CLR @r1',
            'FUN set_A3_A4 $r0 $r1',
            'FUN clear_B',
            '^comment line 19     Clear_A_And_B();',
            'FUN clear_A_B',
            '^comment line 20     Clear_B();',
            'FUN clear_B',
            '^comment line 21     break;',
            'FIN',
            '^comment line 22 case 4: // Swap_A_and_B',
            '__switch1_3:',
            '^comment line 23     Clear_A_And_B();',
            'FUN clear_A_B',
            '^comment line 24     a++;',
            'INC @a',
            '^comment line 25     Swap_A_and_B();',
            'FUN swap_A_and_B',
            '^comment line 26     a++;',
            'INC @a',
            '^comment line 27     Set_B4(0);',
            'CLR @r0',
            'FUN set_B4 $r0',
            '^comment line 28     Set_A3(0);',
            'CLR @r0',
            'FUN set_A3 $r0',
            '^comment line 29     break;',
            'FIN',
            '^comment line 30 case 5: // metaDoNothing',
            '__switch1_4:',
            '^comment line 31     Clear_A_And_B();',
            'FUN clear_A_B',
            '^comment line 32     Send_All_To_Address_In_B();',
            'FUN send_All_to_Address_in_B',
            '^comment line 33     Clear_A_And_B();',
            'FUN clear_A_B',
            '^comment line 34     break;',
            'FIN',
            '^comment line 35 case 6: // metaUnknowSuperRegisterA',
            '__switch1_5:',
            '^comment line 36     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            'FUN set_B3 $a',
            '^comment line 37     Put_Last_Block_GSig_In_A();',
            'FUN Put_Last_Block_GSig_In_A',
            '^comment line 38     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            'FUN set_B3 $a',
            '^comment line 39     break;',
            'FIN',
            '^comment line 40 case 7: // metaUnknowSuperRegisterB',
            '__switch1_6:',
            '^comment line 41     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            'FUN set_B3 $a',
            '^comment line 42     OR_B_with_A();',
            'FUN OR_B_with_A',
            '^comment line 43     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            'FUN set_B3 $a',
            '^comment line 44     break;',
            'FIN',
            '^comment line 45 case 8: // metaUB1ZB2ZB3ZB4',
            '__switch1_7:',
            '^comment line 46     Set_B1_B2(a, 0);',
            'CLR @r0',
            'FUN set_B1_B2 $a $r0',
            '^comment line 47     B_To_Address_Of_Tx_In_A();',
            'FUN B_to_Address_of_Tx_in_A',
            '^comment line 48     Set_B1(a); Set_B2(0); Set_B3(0); Set_B4(0);',
            'FUN set_B1 $a',
            'CLR @r0',
            'FUN set_B2 $r0',
            'CLR @r0',
            'FUN set_B3 $r0',
            'CLR @r0',
            'FUN set_B4 $r0',
            '^comment line 49     break;',
            'FIN'
        ]
        const optCode = [
            '^declare r0',
            '^declare r1',
            '^declare r2',
            '^declare testID',
            '^declare a',
            '^declare b',
            '',
            '^comment line 7 switch (testID) {',
            'SET @r0 #0000000000000001',
            'BEQ $testID $r0 :__switch1_0',
            'SET @r0 #0000000000000002',
            'BEQ $testID $r0 :__switch1_1',
            'SET @r0 #0000000000000003',
            'BEQ $testID $r0 :__switch1_2',
            'SET @r0 #0000000000000004',
            'BEQ $testID $r0 :__switch1_3',
            'SET @r0 #0000000000000005',
            'BEQ $testID $r0 :__switch1_4',
            'SET @r0 #0000000000000006',
            'BEQ $testID $r0 :__switch1_5',
            'SET @r0 #0000000000000007',
            'BEQ $testID $r0 :__switch1_6',
            'SET @r0 #0000000000000008',
            'BEQ $testID $r0 :__switch1_7',
            'FIN',
            '^comment line 8 case 1: // Clear_A',
            '__switch1_0:',
            '^comment line 9     Clear_A();',
            'FUN clear_A',
            '^comment line 10     Set_A2(0);',
            'CLR @r0',
            '^comment line 11     Clear_A();',
            '^comment line 12     break;',
            'FIN',
            '^comment line 13 case 2: // Clear_B',
            '__switch1_1:',
            '^comment line 14     Clear_B();',
            'FUN clear_B',
            '^comment line 15     Set_B4(0);',
            'CLR @r0',
            '^comment line 16     Clear_B();',
            '^comment line 17 case 3: // Clear_A_And_B',
            '__switch1_2:',
            '^comment line 18     Set_A1_A2(0',
            'CLR @r0',
            'CLR @r1',
            'FUN set_A1_A2 $r0 $r1',
            'FUN set_A3_A4 $r0 $r1',
            'FUN clear_B',
            '^comment line 19     Clear_A_And_B();',
            '^comment line 20     Clear_B();',
            '^comment line 21     break;',
            'FIN',
            '^comment line 22 case 4: // Swap_A_and_B',
            '__switch1_3:',
            '^comment line 23     Clear_A_And_B();',
            'FUN clear_A_B',
            '^comment line 24     a++;',
            'INC @a',
            '^comment line 25     Swap_A_and_B();',
            'FUN swap_A_and_B',
            '^comment line 26     a++;',
            'INC @a',
            '^comment line 27     Set_B4(0);',
            'CLR @r0',
            'FUN set_B4 $r0',
            '^comment line 28     Set_A3(0);',
            'FUN set_A3 $r0',
            '^comment line 29     break;',
            'FIN',
            '^comment line 30 case 5: // metaDoNothing',
            '__switch1_4:',
            '^comment line 31     Clear_A_And_B();',
            'FUN clear_A_B',
            '^comment line 32     Send_All_To_Address_In_B();',
            'FUN send_All_to_Address_in_B',
            '^comment line 33     Clear_A_And_B();',
            '^comment line 34     break;',
            'FIN',
            '^comment line 35 case 6: // metaUnknowSuperRegisterA',
            '__switch1_5:',
            '^comment line 36     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            'FUN set_B3 $a',
            '^comment line 37     Put_Last_Block_GSig_In_A();',
            'FUN Put_Last_Block_GSig_In_A',
            '^comment line 38     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            '^comment line 39     break;',
            'FIN',
            '^comment line 40 case 7: // metaUnknowSuperRegisterB',
            '__switch1_6:',
            '^comment line 41     Set_A3(a); Set_B3(a);',
            'FUN set_A3 $a',
            'FUN set_B3 $a',
            '^comment line 42     OR_B_with_A();',
            'FUN OR_B_with_A',
            '^comment line 43     Set_A3(a); Set_B3(a);',
            'FUN set_B3 $a',
            '^comment line 44     break;',
            'FIN',
            '^comment line 45 case 8: // metaUB1ZB2ZB3ZB4',
            '__switch1_7:',
            '^comment line 46     Set_B1_B2(a, 0);',
            'CLR @r0',
            'FUN set_B1_B2 $a $r0',
            '^comment line 47     B_To_Address_Of_Tx_In_A();',
            'FUN B_to_Address_of_Tx_in_A',
            '^comment line 48     Set_B1(a); Set_B2(0); Set_B3(0); Set_B4(0);',
            'FUN set_B1 $a',
            '^comment line 49     break;',
            'FIN'
        ]
        const result = new CONTRACT(code).optimize()
        expect(result).toEqual(optCode)
    })
})
